name: Build Vite React App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20  # or whatever version you use

      - name: Install dependencies
        run: npm i

      - name: Build Vite app
        run: npm run build
